name: Release on Tag
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    # branches: [ master ]
  
jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Checkout repo
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Makefile
      run: mkdir build && cd build && qmake -makefile -o Makefile "CONFIG+=release" ../GBAATM-Rebirth.pro
    - name: Build
      run: make
    - name: Upload
      uses: actions/upload-artifact@v2
      #-preview
      with:
        name: GBAATM-Rebirth-${{ steps.commit_num_step.outputs.commit_num }} Linux
        path: build/GBAATM-Rebirth

  build-windows:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Checkout repo
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Makefile
      run: mkdir build && cd build && qmake -makefile -o Makefile "CONFIG+=release" ../GBAATM-Rebirth.pro
    - name: Build
      run: make
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: GBAATM-Rebirth-${{ steps.commit_num_step.outputs.commit_num }} Win
        path: build/GBAATM-Rebirth.exe

  build-macos:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Checkout repo
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
     - name: Makefile
      run: mkdir build && cd build && qmake -makefile -o Makefile "CONFIG+=release" ../GBAATM-Rebirth.pro
    - name: Build
      run: make
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: GBAATM-Rebirth-${{ steps.commit_num_step.outputs.commit_num }} OSX
        path: build/GBAATM-Rebirth.dmg

